### ISSUE TITLE
안녕하세요 챗봇관련하여 문의 드립니다 ㅠ 

### ISSUE THREAD

**Issue by kazuya023** [RYUUUUUUU/Self-Development-BOT#2]
안녕하세요 개발자님
개발자님의 소스를 보고 카카오톡 챗봇을 구현하려고 하고 있는데..

mysql 연결이 제대로 안되서.. .몇일간 계속 시도해보다가 문의글을 남겨봅니다.

cafe24 웹호스팅을 사용하고 있고요.. 카카오톡 챗봇 이외의 다른 프로그램들은 잘 연결해서 사용중입니다..

mysql_query  이것만 날리면

"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요. "

이렇게 나와서 미칠지경입니다 ㅠㅠ

도와주세요

아래는 소스 입니다.. 

nclude("functions/echoKakao.php");
$servername = "localhost";
$username = "douniq";
$password = "**************";
$dbname = "douniq";
$mysqli = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($mysqli->connect_error) {
die("Connection failed: " . $mysqli->connect_error);
writelog($user_key, "db 접속에 실패하였습니다");
}
// 요청을 받아 저장
$data = json_decode(file_get_contents('php://input'), true);
$content = $data["content"];
if ($result = $mysqli->query("SELECT * FROM Autodesk_partner")) {
while($row = $result->fetch_row()) {
$test_result = $row[0];
$start = array(
"message" => array(
"text" => $test_result)
);
}
}
echo(json_encode($start));

바쁘시겠지만 답변 부탁드립니다

감사합니다!!

**Comment by ug00gu** [comment]
안녕하세요

저도 DB문제가 되는 경우가 있었는데, 일단 로컬에서 mySQL 연동 후에 php파일로 뿌려주는걸 확인한번 해보세요

단순하게 생각해서 db에 123이라는 스트링을 php를 통해 웹에서 띄우기만 하면 챗봇은 90프로 이상 끝이라고 보시면 됩니다

언제든 또 연락주시면 답변해드리겠습니다

2018년 7월 26일 오후 2:53, kazuya023 <notifications@github.com>님이 작성:

**Comment by kazuya023** [comment]
정말 너무너무 감사합니다 개발자님!!!

말씀하신대로 일단 로컬에서 연동을 다시 처음부터 꼼꼼히 시도해봤더니..

문제가 있었더라구요~ !!! 

좋은 하루되시고 또 궁금한점 있으면 문의드리도록 하겠습니다. 

다시한번 감사드립니다 💯 )
